### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by frederico-miranda** [ricardovaltierra/slackbot#1]
At mb_ruby/bot.rb,
line 30: The 'GET' HTTP request could fail, but there are no handlers for that failure.

The more dependencies your project has, the harder it will be to read, understand and maintain it. This one file requires 'imgur2', 'wolfram', 'screencap' (APIs that query servers). Refactoring this to multiple files will make the project easier to read and maintain.

Erase all of the test methods on bot.rb
Include the implemented methods on help with a description
Verify if it is possible to run all of the methods directly from the Bot class
Verify that all of the gems are used, deleting the ones that are not
Include on .env file the screenshot API token and the wolfram token
Update README.md 

Using NLP (Natural Language Processing) might enhance your chat bot.

**Comment by ricardovaltierra** [comment]
Done the required corrections proposed on the issue
